## Terminal: gp init
## Generate this yml script

## Scripting
## env | grep AWS-SolutionsArch
## Get $THEIA_WORKSPACE_ROOT

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: aws-cli
    env: AWS_CLI_AUTO_PROMPT: on-partial
    before: 
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
      unzip awscliv2.zip 
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# # Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
