#!/usr/bin/env bash

# # Check if at least one argument is provided
# if [ $# -eq 0 ]; then
#     echo "No bucket name provided."
#     exit 1
# fi

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
# aws s3api create-bucket --bucket $1
# https://stackoverflow.com/questions/49174673/aws-s3api-create-bucket-bucket-make-exception
# Note: No Spacing after \
aws s3api create-bucket \
    --bucket $BUCKET_NAME \
    --create-bucket-configuration LocationConstraint=ap-southeast-1 \
    --query Location \
    --output text