#!/usr/bin/env bash

echo "== list objects"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
# https://stackoverflow.com/questions/49174673/aws-s3api-create-bucket-bucket-make-exception
# Note: No Spacing after \
aws s3api list-objects-v2 \
    --bucket $BUCKET_NAME
