#!/usr/bin/env bash
echo "== sync"
# Exit immediately if any command returns a non-zero status
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi


# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix eg. ./bucket my-bucket-name my-filename-prefix"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# Files Stored
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Create Output Folder
mkdir -p $OUTPUT_DIR

# Generate a random number to determin how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    # Generate random data and write to file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null

    # echo "Create $FILENAME"
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files